// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartFlashcardAPI.Data;

#nullable disable

namespace SmartFlashcardAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420060211_AddIsNotifiedToOwner")]
    partial class AddIsNotifiedToOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SessionId", "CreatedAt")
                        .HasDatabaseName("IX_AiChat_UserSession");

                    b.ToTable("AiChatHistory");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AiUsageLogs_CreatedAt");

                    b.HasIndex("PromptType")
                        .HasDatabaseName("IX_AiUsageLogs_PromptType");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_AiUsageLogs_UserDate");

                    b.ToTable("AiUsageLogs");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.ContentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsNotifiedToOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ContentReports_Status");

                    b.ToTable("ContentReports");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GoogleSheetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("vi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Decks_UserId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.DeckShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultPermission")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.ToTable("DeckShares");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.DeckSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberId")
                        .HasDatabaseName("IX_DeckSubscriptions_Subscriber");

                    b.HasIndex("DeckId", "SubscriberId")
                        .IsUnique()
                        .HasDatabaseName("IX_DeckSubscriptions_DeckUser");

                    b.ToTable("DeckSubscriptions");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<double>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.5);

                    b.Property<string>("ExampleText")
                        .HasColumnType("text");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Repetition")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WordSenseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("WordSenseId");

                    b.HasIndex("UserId", "DeckId")
                        .HasDatabaseName("IX_Flashcards_UserDeck")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UserId", "NextReviewDate")
                        .HasDatabaseName("IX_Flashcards_NextReview")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("IX_Flashcards_UpdatedAt");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.HomonymGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("LemmaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LemmaId");

                    b.ToTable("HomonymGroups");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Lemma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LemmaText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LemmaText", "Language")
                        .IsUnique();

                    b.ToTable("Lemmas");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.ReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId")
                        .HasDatabaseName("IX_ReviewLogs_FlashcardId");

                    b.HasIndex("UserId", "ReviewedAt")
                        .HasDatabaseName("IX_ReviewLogs_UserDate");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.SemanticCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SemanticClusters");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.SharedImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("IX_SharedImages_Keyword")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UserId");

                    b.ToTable("SharedImages");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.SyncMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsSynced")
                        .HasDatabaseName("IX_Sync_UserPending")
                        .HasFilter("\"IsSynced\" = false");

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AiUsageResetDate")
                        .HasColumnType("date");

                    b.Property<int>("AiUsageToday")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("vi");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Free");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.WordEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HomonymGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LemmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HomonymGroupId");

                    b.HasIndex("LemmaId");

                    b.HasIndex("PartOfSpeech");

                    b.ToTable("WordEntries");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.WordSense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DefinitionVi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Example")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("SemanticClusterId")
                        .HasColumnType("uuid");

                    b.Property<int>("SenseOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SemanticClusterId");

                    b.HasIndex("WordEntryId");

                    b.ToTable("WordSenses");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.WordVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LemmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariantText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VariantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LemmaId");

                    b.HasIndex("VariantText");

                    b.ToTable("WordVariants");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.AiChatMessage", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany("AiChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.AiUsageLog", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.ContentReport", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Deck", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.DeckShare", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.Deck", "Deck")
                        .WithMany("DeckShares")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.DeckSubscription", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.Deck", "Deck")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Flashcard", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.Deck", "Deck")
                        .WithMany("Flashcards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartFlashcardAPI.Models.Entities.WordSense", "WordSense")
                        .WithMany()
                        .HasForeignKey("WordSenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deck");

                    b.Navigation("User");

                    b.Navigation("WordSense");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.HomonymGroup", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.Lemma", "Lemma")
                        .WithMany("HomonymGroups")
                        .HasForeignKey("LemmaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lemma");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.ReviewLog", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.Flashcard", "Flashcard")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.SharedImage", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.SyncMetadata", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.WordEntry", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.HomonymGroup", "HomonymGroup")
                        .WithMany("Entries")
                        .HasForeignKey("HomonymGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartFlashcardAPI.Models.Entities.Lemma", "Lemma")
                        .WithMany("WordEntries")
                        .HasForeignKey("LemmaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HomonymGroup");

                    b.Navigation("Lemma");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.WordSense", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.SemanticCluster", "SemanticCluster")
                        .WithMany()
                        .HasForeignKey("SemanticClusterId");

                    b.HasOne("SmartFlashcardAPI.Models.Entities.WordEntry", "WordEntry")
                        .WithMany("Senses")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SemanticCluster");

                    b.Navigation("WordEntry");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.WordVariant", b =>
                {
                    b.HasOne("SmartFlashcardAPI.Models.Entities.Lemma", "Lemma")
                        .WithMany("Variants")
                        .HasForeignKey("LemmaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lemma");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Deck", b =>
                {
                    b.Navigation("DeckShares");

                    b.Navigation("Flashcards");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Flashcard", b =>
                {
                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.HomonymGroup", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.Lemma", b =>
                {
                    b.Navigation("HomonymGroups");

                    b.Navigation("Variants");

                    b.Navigation("WordEntries");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.User", b =>
                {
                    b.Navigation("AiChatMessages");

                    b.Navigation("Decks");

                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("SmartFlashcardAPI.Models.Entities.WordEntry", b =>
                {
                    b.Navigation("Senses");
                });
#pragma warning restore 612, 618
        }
    }
}
